// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: proto/shorturl.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Resp) Reset() {
	*x = Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{0}
}

func (x *Resp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Resp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Resp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Curl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Url           string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Curl) Reset() {
	*x = Curl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Curl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Curl) ProtoMessage() {}

func (x *Curl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Curl.ProtoReflect.Descriptor instead.
func (*Curl) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{1}
}

func (x *Curl) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Curl) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SetLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SetLinkRequest) Reset() {
	*x = SetLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLinkRequest) ProtoMessage() {}

func (x *SetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLinkRequest.ProtoReflect.Descriptor instead.
func (*SetLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{2}
}

func (x *SetLinkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SetLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R        *Resp  `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Shorturl string `protobuf:"bytes,2,opt,name=shorturl,proto3" json:"shorturl,omitempty"`
}

func (x *SetLinkResponse) Reset() {
	*x = SetLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLinkResponse) ProtoMessage() {}

func (x *SetLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLinkResponse.ProtoReflect.Descriptor instead.
func (*SetLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{3}
}

func (x *SetLinkResponse) GetR() *Resp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *SetLinkResponse) GetShorturl() string {
	if x != nil {
		return x.Shorturl
	}
	return ""
}

type SetBatchUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []*Curl `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *SetBatchUrlRequest) Reset() {
	*x = SetBatchUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBatchUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBatchUrlRequest) ProtoMessage() {}

func (x *SetBatchUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBatchUrlRequest.ProtoReflect.Descriptor instead.
func (*SetBatchUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{4}
}

func (x *SetBatchUrlRequest) GetUrls() []*Curl {
	if x != nil {
		return x.Urls
	}
	return nil
}

type SetBatchUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R    *Resp   `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Urls []*Curl `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *SetBatchUrlResponse) Reset() {
	*x = SetBatchUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetBatchUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBatchUrlResponse) ProtoMessage() {}

func (x *SetBatchUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBatchUrlResponse.ProtoReflect.Descriptor instead.
func (*SetBatchUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{5}
}

func (x *SetBatchUrlResponse) GetR() *Resp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *SetBatchUrlResponse) GetUrls() []*Curl {
	if x != nil {
		return x.Urls
	}
	return nil
}

type GetOwnUrlListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetOwnUrlListRequest) Reset() {
	*x = GetOwnUrlListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOwnUrlListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnUrlListRequest) ProtoMessage() {}

func (x *GetOwnUrlListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnUrlListRequest.ProtoReflect.Descriptor instead.
func (*GetOwnUrlListRequest) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{6}
}

type GetOwnUrlListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R    *Resp   `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Urls []*Curl `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *GetOwnUrlListResponse) Reset() {
	*x = GetOwnUrlListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOwnUrlListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOwnUrlListResponse) ProtoMessage() {}

func (x *GetOwnUrlListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOwnUrlListResponse.ProtoReflect.Descriptor instead.
func (*GetOwnUrlListResponse) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{7}
}

func (x *GetOwnUrlListResponse) GetR() *Resp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *GetOwnUrlListResponse) GetUrls() []*Curl {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DelOwnUrlListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls []string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
}

func (x *DelOwnUrlListRequest) Reset() {
	*x = DelOwnUrlListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelOwnUrlListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOwnUrlListRequest) ProtoMessage() {}

func (x *DelOwnUrlListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOwnUrlListRequest.ProtoReflect.Descriptor instead.
func (*DelOwnUrlListRequest) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{8}
}

func (x *DelOwnUrlListRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type DelOwnUrlListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R *Resp `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
}

func (x *DelOwnUrlListResponse) Reset() {
	*x = DelOwnUrlListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelOwnUrlListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOwnUrlListResponse) ProtoMessage() {}

func (x *DelOwnUrlListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOwnUrlListResponse.ProtoReflect.Descriptor instead.
func (*DelOwnUrlListResponse) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{9}
}

func (x *DelOwnUrlListResponse) GetR() *Resp {
	if x != nil {
		return x.R
	}
	return nil
}

type GetLinkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Surl string `protobuf:"bytes,1,opt,name=surl,proto3" json:"surl,omitempty"`
}

func (x *GetLinkRequest) Reset() {
	*x = GetLinkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRequest) ProtoMessage() {}

func (x *GetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRequest.ProtoReflect.Descriptor instead.
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{10}
}

func (x *GetLinkRequest) GetSurl() string {
	if x != nil {
		return x.Surl
	}
	return ""
}

type GetLinkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R   *Resp  `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetLinkResponse) Reset() {
	*x = GetLinkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkResponse) ProtoMessage() {}

func (x *GetLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkResponse.ProtoReflect.Descriptor instead.
func (*GetLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{11}
}

func (x *GetLinkResponse) GetR() *Resp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *GetLinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{12}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R *Resp `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{13}
}

func (x *PingResponse) GetR() *Resp {
	if x != nil {
		return x.R
	}
	return nil
}

type GetStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{14}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R     *Resp `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	Users int32 `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
	Surls int32 `protobuf:"varint,3,opt,name=surls,proto3" json:"surls,omitempty"`
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_proto_rawDescGZIP(), []int{15}
}

func (x *GetStatsResponse) GetR() *Resp {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *GetStatsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *GetStatsResponse) GetSurls() int32 {
	if x != nil {
		return x.Surls
	}
	return 0
}

var File_proto_shorturl_proto protoreflect.FileDescriptor

var file_proto_shorturl_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x65, 0x6d, 0x6f, 0x22, 0x42, 0x0a, 0x04,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x3f, 0x0a, 0x04, 0x43, 0x75, 0x72, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x22, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x47, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52,
	0x01, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x22, 0x34,
	0x0a, 0x12, 0x53, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x75, 0x72, 0x6c, 0x52, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x22, 0x4f, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x01, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x52, 0x01, 0x72, 0x12, 0x1e, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x75, 0x72, 0x6c, 0x52,
	0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x55,
	0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x51, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x55, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x01, 0x72,
	0x12, 0x1e, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x43, 0x75, 0x72, 0x6c, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73,
	0x22, 0x2a, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x4f, 0x77, 0x6e, 0x55, 0x72, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x22, 0x31, 0x0a, 0x15,
	0x44, 0x65, 0x6c, 0x4f, 0x77, 0x6e, 0x55, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x01, 0x72, 0x22,
	0x24, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x73, 0x75, 0x72, 0x6c, 0x22, 0x3d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52,
	0x01, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x28, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x01, 0x72, 0x22, 0x11, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x58, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x52, 0x01, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x75, 0x72, 0x6c, 0x73, 0x32, 0xbc, 0x03, 0x0a, 0x08, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x36, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x4c, 0x69,
	0x6e, 0x6b, 0x12, 0x14, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x4c, 0x69, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x53, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x36, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x14, 0x2e, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x53, 0x65,
	0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x4f, 0x77, 0x6e, 0x55, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x55, 0x72, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x4f, 0x77, 0x6e, 0x55, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x4f, 0x77, 0x6e, 0x55,
	0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65,
	0x6c, 0x4f, 0x77, 0x6e, 0x55, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x4f, 0x77, 0x6e,
	0x55, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2d, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x11, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x15, 0x2e, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x75, 0x72, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_shorturl_proto_rawDescOnce sync.Once
	file_proto_shorturl_proto_rawDescData = file_proto_shorturl_proto_rawDesc
)

func file_proto_shorturl_proto_rawDescGZIP() []byte {
	file_proto_shorturl_proto_rawDescOnce.Do(func() {
		file_proto_shorturl_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_shorturl_proto_rawDescData)
	})
	return file_proto_shorturl_proto_rawDescData
}

var file_proto_shorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_shorturl_proto_goTypes = []interface{}{
	(*Resp)(nil),                  // 0: demo.Resp
	(*Curl)(nil),                  // 1: demo.Curl
	(*SetLinkRequest)(nil),        // 2: demo.SetLinkRequest
	(*SetLinkResponse)(nil),       // 3: demo.SetLinkResponse
	(*SetBatchUrlRequest)(nil),    // 4: demo.SetBatchUrlRequest
	(*SetBatchUrlResponse)(nil),   // 5: demo.SetBatchUrlResponse
	(*GetOwnUrlListRequest)(nil),  // 6: demo.GetOwnUrlListRequest
	(*GetOwnUrlListResponse)(nil), // 7: demo.GetOwnUrlListResponse
	(*DelOwnUrlListRequest)(nil),  // 8: demo.DelOwnUrlListRequest
	(*DelOwnUrlListResponse)(nil), // 9: demo.DelOwnUrlListResponse
	(*GetLinkRequest)(nil),        // 10: demo.GetLinkRequest
	(*GetLinkResponse)(nil),       // 11: demo.GetLinkResponse
	(*PingRequest)(nil),           // 12: demo.PingRequest
	(*PingResponse)(nil),          // 13: demo.PingResponse
	(*GetStatsRequest)(nil),       // 14: demo.GetStatsRequest
	(*GetStatsResponse)(nil),      // 15: demo.GetStatsResponse
}
var file_proto_shorturl_proto_depIdxs = []int32{
	0,  // 0: demo.SetLinkResponse.r:type_name -> demo.Resp
	1,  // 1: demo.SetBatchUrlRequest.urls:type_name -> demo.Curl
	0,  // 2: demo.SetBatchUrlResponse.r:type_name -> demo.Resp
	1,  // 3: demo.SetBatchUrlResponse.urls:type_name -> demo.Curl
	0,  // 4: demo.GetOwnUrlListResponse.r:type_name -> demo.Resp
	1,  // 5: demo.GetOwnUrlListResponse.urls:type_name -> demo.Curl
	0,  // 6: demo.DelOwnUrlListResponse.r:type_name -> demo.Resp
	0,  // 7: demo.GetLinkResponse.r:type_name -> demo.Resp
	0,  // 8: demo.PingResponse.r:type_name -> demo.Resp
	0,  // 9: demo.GetStatsResponse.r:type_name -> demo.Resp
	2,  // 10: demo.ShortUrl.SetLink:input_type -> demo.SetLinkRequest
	10, // 11: demo.ShortUrl.GetLink:input_type -> demo.GetLinkRequest
	4,  // 12: demo.ShortUrl.SetBatchUrl:input_type -> demo.SetBatchUrlRequest
	6,  // 13: demo.ShortUrl.GetOwnUrlList:input_type -> demo.GetOwnUrlListRequest
	8,  // 14: demo.ShortUrl.DelOwnUrlList:input_type -> demo.DelOwnUrlListRequest
	12, // 15: demo.ShortUrl.Ping:input_type -> demo.PingRequest
	14, // 16: demo.ShortUrl.GetStats:input_type -> demo.GetStatsRequest
	3,  // 17: demo.ShortUrl.SetLink:output_type -> demo.SetLinkResponse
	11, // 18: demo.ShortUrl.GetLink:output_type -> demo.GetLinkResponse
	5,  // 19: demo.ShortUrl.SetBatchUrl:output_type -> demo.SetBatchUrlResponse
	7,  // 20: demo.ShortUrl.GetOwnUrlList:output_type -> demo.GetOwnUrlListResponse
	9,  // 21: demo.ShortUrl.DelOwnUrlList:output_type -> demo.DelOwnUrlListResponse
	13, // 22: demo.ShortUrl.Ping:output_type -> demo.PingResponse
	15, // 23: demo.ShortUrl.GetStats:output_type -> demo.GetStatsResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_shorturl_proto_init() }
func file_proto_shorturl_proto_init() {
	if File_proto_shorturl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_shorturl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Curl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBatchUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetBatchUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOwnUrlListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOwnUrlListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelOwnUrlListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelOwnUrlListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLinkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLinkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_shorturl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shorturl_proto_goTypes,
		DependencyIndexes: file_proto_shorturl_proto_depIdxs,
		MessageInfos:      file_proto_shorturl_proto_msgTypes,
	}.Build()
	File_proto_shorturl_proto = out.File
	file_proto_shorturl_proto_rawDesc = nil
	file_proto_shorturl_proto_goTypes = nil
	file_proto_shorturl_proto_depIdxs = nil
}
